name: Import Accessibility Posts

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 12 * * MON"

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Use Deno Version 1.19.2
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.19.2"
      - name: Import Latest Posts
        run: deno run --allow-read --allow-env --allow-net src/index.ts
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
