name: Import Accessibility Posts

on:
  schedule:
    - cron: '0 12 * * MON'

jobs:
  import:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.19.2]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Import Latest Posts
        run: deno run --allow-read --allow-env --allow-net src/index.ts
